# This configuration sets up a Traefik edge router with Gitea SCM + MySQL
# containers, using a specific IP address, with SSL certificates provided
# by LetsEncrypt. You must supply the required environment variables via
# the ./.env file.

version: "3.3"

networks:
  web4:
    # You must create this network manually, and ensure it is routable:
    #   docker network create --gateway 10.10.4.1 --subnet 10.10.4.0/24 web4
    # You can change the name, but ensure that's reflected across this file.
    external: true
  db:
    external: false

volumes:
  gitea:
    driver: local
  db:
    driver: local

services:
  traefik:
    image: "traefik:v2.3.2"
    container_name: "traefik"
    restart: unless-stopped
    environment:
      # This setup uses a DNS domain hosted at DigitalOcean. You'll need to make
      # the necessary adjustments if your DNS is managed by another provider.
      DO_AUTH_TOKEN: "${DO_AUTH_TOKEN}"
    command:
      - "--providers.docker=true"
      - "--entryPoints.ssh.address=:22"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedByDefault=false"
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker.network=web4"
      - "--certificatesResolvers.le.acme.email=${LE_EMAIL}"
      - "--certificatesResolvers.le.acme.storage=/acme.json"
      - "--certificatesResolvers.le.acme.dnsChallenge=true"
      - "--certificatesResolvers.le.acme.dnschallenge.provider=digitalocean"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web4"
      # Redirect all HTTP traffic to HTTPS on this IP
      - "traefik.http.routers.traefik.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.permanent=true"
      # Route for Traefik Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=le"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=traefik:$$apr1$$qu17ZAy1$$CV4OFN7oV3vRXaSEpPpeA0"
      # Above will set up username 'traefik' with password 'traefik', which of course you'll want to
      # change. Use below command from Ubuntu CLI to generate your very own username/password string:
      #     echo $(htpasswd -nb <username> <password>) | sed -e s/\\$/\\$\\$/g
      #   Example:
      #     echo $(htpasswd -nb traefik MyPwd/80,1) | sed -e s/\\$/\\$\\$/g
    networks:
      web4:
        ipv4_address: 10.10.4.2  # Point all DNS domains to this address
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"

  gitea:
    image: "gitea/gitea:1.12.5"
    container_name: "gitea"
    restart: unless-stopped
    environment:
      - DOMAIN=${SITE_DOMAIN}
      - SSH_DOMAIN=${SITE_DOMAIN}
      - SSH_PORT=22
      - SSH_LISTEN_PORT=22
      - ROOT_URL=https://${SITE_DOMAIN}/
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web4"
      # The HTTPS service
      - "traefik.http.routers.giteaWeb.rule=Host(`${SITE_DOMAIN}`)"
      - "traefik.http.routers.giteaWeb.entrypoints=websecure"
      - "traefik.http.routers.giteaWeb.tls=true"
      - "traefik.http.routers.giteaWeb.tls.certresolver=le"
      - "traefik.http.routers.giteaWeb.service=giteaWebSvc"
      - "traefik.http.services.giteaWebSvc.loadbalancer.server.port=3000"
      # The SSH service
      - "traefik.tcp.routers.giteaSSH.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.giteaSSH.entrypoints=ssh"
      - "traefik.tcp.routers.giteaSSH.service=giteaSSHSvc"
      - "traefik.tcp.services.giteaSSHSvc.loadbalancer.server.port=22"
    networks:
      - web4  # Will use next available IP in 10.10.4.0/24
      - db
    ports:
      - "3000"
      - "22"
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - traefik
      - db

  db:
    image: "mysql:8.0.22"
    container_name: "mysql"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=gitea
    networks:
      - db
    volumes:
      - db:/var/lib/mysql

# To run:
# vi .env
# touch acme.json
# chmod 0600 acme.json
# docker-compose --verbose up -d
