#!/bin/bash
# luxrestore

BAK=luxbackup.tgz
if [[ ! -e "$BAK" ]]; then
    printf "Missing '$BAK' file\n"
    exit 1
fi

printf "\nRestore Gitea\n\n"
printf "  1. Ensure old Traefik, Gitea and MySQL containers are gone\n"
printf "  2. Ensure old volumes have been pruned\n"
printf "  3. Restore from lunxbackup.tgz file\n"
printf "  4. Restart all\n\n"
msg="Proceed? Y/N "
read -p "$msg" -n 1 && [[ ! $REPLY =~ ^[Yy]$ ]] && { printf "\nAborted.\n" && exit 1 ; }
printf "\n"

docker-compose down
docker volume rm lux_db
docker volume rm lux_gitea
printf "Restoring volumes, and files ...\n"
sudo tar -C / -xf $BAK
sudo mv /.env .
sudo mv /acme.json .
docker-compose --verbose up -d
printf "Done\n"
exit 0
